version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "fairychess"
      POSTGRES_USER: "fairychess"
      POSTGRES_DB: "fairychess"
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data 
    networks:
      - fairy-chess-network
   
  # fairy-chess:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - fairy-chess-network    
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "fairychess"
      PGADMIN_DEFAULT_PASSWORD: "fairychess"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - fairy-chess-network

networks: 
  fairy-chess-network:
    driver: bridge